// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task1.Models;

namespace Task1.Migrations
{
    [DbContext(typeof(Task1Context))]
    partial class Task1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Polish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task1.Models.Osoba", b =>
                {
                    b.Property<int>("OsobaId")
                        .HasColumnType("int")
                        .HasColumnName("osoba_id");

                    b.Property<DateTime?>("DataProd")
                        .HasColumnType("date")
                        .HasColumnName("data_prod");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nazwisko");

                    b.Property<int>("SamochodId")
                        .HasColumnType("int")
                        .HasColumnName("samochod_id");

                    b.HasKey("OsobaId");

                    b.HasIndex("SamochodId");

                    b.ToTable("OSOBA");
                });

            modelBuilder.Entity("Task1.Models.Samochod", b =>
                {
                    b.Property<int>("SamochodId")
                        .HasColumnType("int")
                        .HasColumnName("samochod_id");

                    b.Property<decimal>("Cena")
                        .HasColumnType("money")
                        .HasColumnName("cena");

                    b.Property<decimal>("Pojemnosc")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("pojemnosc");

                    b.HasKey("SamochodId");

                    b.ToTable("SAMOCHOD");
                });

            modelBuilder.Entity("Task1.Models.Osoba", b =>
                {
                    b.HasOne("Task1.Models.Samochod", "Samochod")
                        .WithMany("Osoby")
                        .HasForeignKey("SamochodId")
                        .HasConstraintName("FK__OSOBY__samochod___2B3F6F97")
                        .IsRequired();

                    b.Navigation("Samochod");
                });

            modelBuilder.Entity("Task1.Models.Samochod", b =>
                {
                    b.Navigation("Osoby");
                });
#pragma warning restore 612, 618
        }
    }
}
